### ISSUE TITLE
Polygon not splitting correctly when created in counter clockwise order

### ISSUE THREAD

**Issue by thealves** [rowanwins/polygon-splitter#7]
When creating a polygon in clockwise order it splits correctly as shown below
![image](https://user-images.githubusercontent.com/55852987/148120782-0923a48e-bdc1-4fd3-a78e-b1e9b677c744.png)

When creating a polygon in counter clockwise it just duplicates the polygon and adds the space that was in the outer side of the polygon as part of it. As shown below
![image](https://user-images.githubusercontent.com/55852987/148120876-dd9fd08a-2345-4baf-9822-845eb90ceb6f.png)

**Comment by rowanwins** [comment]
Yeah I think currently this algorithm is sensitive to winding order - I need to spend some time working out how to overcome that... I think during the initial processing I can compute the winding order and then pass that through to subsequent steps.

**Comment by rowanwins** [comment]
@thealves I've just published 0.0.6 which I believe resolves this issue, please reopen the ticket if required.

**Comment by thealves** [comment]
still have the issue, just upgraded to 0.0.6 but creating a polygon in counter clockwise, the split doesnt work properly

![image](https://user-images.githubusercontent.com/55852987/148826796-98f69a08-edee-4eed-ae69-f9b49ba85bb8.png)

**Comment by rowanwins** [comment]
@thealves could you please share your geojson inputs, I'm struggling to replicate
